# Generated by Django 3.2 on 2024-02-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_remove_lesson_is_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='shortdescription',
            new_name='vehicle',
        ),
    ]
