# Generated by Django 3.2 on 2024-02-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_rename_shortdescription_workshop_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='vehicle',
            new_name='shortdescription',
        ),
    ]
