# Generated by Django 3.2 on 2024-02-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
